[package]
name = "l0"
edition = "2021"
version = "1.0.0"

[dependencies]
axum = "0.7.6"
serde_json = "1.0.128"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
rusqlite = "0.26"
tower = "0.5.1"
http-body-util = "0.1.2"
